name: delete-branch-on-merge-to-develop

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  delete-branch:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'develop' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.pull_request.head.ref != 'develop' &&
      github.event.pull_request.head.ref != 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Delete head branch
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const ref = `heads/${context.payload.pull_request.head.ref}`;
            console.log(`Deleting ${ref}`);
            await github.rest.git.deleteRef({ owner, repo, ref });
